Disable GitHubSecurityLabs/actions-permissions
We disable the GitHubSecurityLabs/actions-permissions action for the
build-push-all job. This is due to observed issues with installing
Python packages within the Docker image being built. An example of the
errors seen:
ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/c9/bc/b7db44f5f39f9d0494071bddae6880eb645970366d0a200022a1a93d57f5/pip-25.0.1-py3-none-any.whl.metadata (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f24939b9590>: Failed to establish a new connection: [Errno -5] Name has no usable address'))

We suspect this is due to the man-in-the-middle approach of the
GitHubSecurityLabs/actions-permissions action so we disable it to
successfully build a final image.